# Generated by Django 3.1.6 on 2021-02-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postitem',
            old_name='toast_roast',
            new_name='roast',
        ),
        migrations.AddField(
            model_name='postitem',
            name='toast',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
