# Generated by Django 3.1.6 on 2021-02-18 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='choose',
            field=models.BooleanField(choices=[(True, 'boast'), (False, 'roast')]),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 17, 1, 37, 930366, tzinfo=utc)),
        ),
    ]
